name: Metrics

on:
  schedule: [{ cron: "0 */12 * * *" }] # каждые 12 часов
  workflow_dispatch:                   # запуск вручную
  push: { branches: ["main"] }         # запуск при пуше в main

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: yttrium699
          template: classic
          filename: metrics.svg
          base: header, activity, repositories, community
          config_timezone: Europe/Moscow
          plugin_traffic: yes

          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          plugin_topics: yes
          plugin_topics_sort: stars
          plugin_topics_mode: mastered
          plugin_topics_limit: 0
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_details: lines, percentage
          plugin_languages_indepth: yes
          plugin_languages_limit: 8
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used, recently-used
          plugin_languages_threshold: 0%

      - name: Commit and push metrics
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add metrics.svg
          git commit -m "chore: update metrics" || echo "No changes to commit"
          git push
